ASP.NET/TVSeriesCalendar/source/TVSeriesCalendar/TVSeriesCalendar/Controllers/ShowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TVSeriesCalendar.Models;

namespace TVSeriesCalendar.Controllers
{
    public class ShowController : Controller
    {
        private IShow showServices;

        public ShowController(IShow ShowServices)
        {
            this.showServices = ShowServices;
        }

        // GET: Show
        [HttpGet]
        public ActionResult Index()
        {
            ShowViewModel model = new ShowViewModel { AllResults = new List<Show>() };
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(ShowViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            ShowViewModel showView = new ShowViewModel { AllResults = showServices.FindAllShowsByName(model.Name) };
            return View(showView);
        }

        [HttpGet]
        public ActionResult TVShowDetails(int id = 0)
        {
            var show = showServices.FindShowById(id);
            Show newShow = new Show {
                ID = show.ID,
                Name = show.Name,
                OriginalName = show.OriginalName,
                FirstAirDate = show.FirstAirDate,
                Popularity = show.Popularity,
                PosterPath = show.PosterPath,
                SimilarTVShows = show.SimilarTVShows,
                Overview = show.Overview,
                OriginCountry = show.OriginCountry,
                VoteAverage = show.VoteAverage,
                VoteCount = show.VoteCount
            };
            return View(newShow);
        }

        [HttpPost]
        public ActionResult TVShowDetails(ShowViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            Show newModel = showServices.FindShowByName(model.Name);
            return View(newModel);
        }

        [HttpGet]
        public ActionResult AddToFavorites(int id)
        {
            Show show = new Show { ID = id };
            showServices.AddToFavorites(id);
            return View(show);
        }

        [HttpPost]
        public ActionResult AddToFavorites(Show model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if(model.ID == 0)
            {
                return View(model.Name);
            }
            showServices.AddToFavorites(model.ID);
            return View();
        }
    }
}

ASP.NET/TVSeriesCalendar/source/TVSeriesCalendar/TVSeriesCalendar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TVSeriesCalendar</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TVSeriesCalendar", "Index", "Show", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Favorites", "Favorites", "Home")</li>
                    <li>@Html.ActionLink("Log in", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="search-container">
            <h2>Find your show here</h2>
            @using (Html.BeginForm())
            {
                @Html.TextBox("Name")
                <input type="submit" value="Find" class="btn btn-default" />
            }
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>TVSeriesCalendar&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>